# Generated by Django 3.2.8 on 2021-10-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espoire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200, null=True)),
                ('number', models.FloatField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('trans_id', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
